dailyfresh/dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('df_user.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('df_goods.urls')),
    url(r'^cart/', include('df_cart.urls')),
    url(r'^order/', include('df_order.urls')),
    url(r'^search/', include('haystack.urls')),
]

dailyfresh/df_cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url('^$', views.cart),
    url(r'^add(\d+)_(\d+)/$', views.add),
    url(r'^edit(\d+)_(\d+)/$', views.edit),
    url(r'^delete(\d+)/$', views.delete),
]

dailyfresh/df_user/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register/$', views.register),
    url(r'^register_handle/$', views.register_handle),
    url(r'^register_exist/$', views.register_exist),
    url(r'^login/$', views.login),
    url(r'^login_handle/$', views.login_handle),
    url(r'^logout/$', views.logout),
    url(r'^info/$', views.info),
    url(r'^order(\d*)/$', views.order),
    url(r'^site/$', views.site),
]

dailyfresh/df_order/models.py
#coding=utf-8
from django.db import models

class OrderInfo(models.Model):
    oid = models.CharField(max_length=20, primary_key=True)
    user = models.ForeignKey('df_user.UserInfo')
    odate = models.DateTimeField(auto_now=True)
    oIsPay = models.BooleanField(default=False)
    ototal = models.DecimalField(max_digits=6, decimal_places=2)
    oaddress = models.CharField(max_length=100,default=None)
    #无法实现：真实支付，物流信息

class OrderDetailInfo(models.Model):
    goods = models.ForeignKey('df_goods.GoodsInfo')
    order = models.ForeignKey(OrderInfo)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    count = models.IntegerField()

dailyfresh/df_user/models.py
from django.db import models

class UserInfo(models.Model):
    uname = models.CharField(max_length=20)
    upwd = models.CharField(max_length=40)
    uemail = models.CharField(max_length=30)
    ushou = models.CharField(max_length=100, default='')
    uaddress = models.CharField(max_length=40, default='')
    uyoubian = models.CharField(max_length=40, default='')
    uphone = models.CharField(max_length=40, default='')

dailyfresh/df_user/views.py
#coding=utf-8
from django.shortcuts import render,redirect
from models import *
from hashlib import sha1
from django.http import JsonResponse,HttpResponseRedirect
from . import user_decorator
from df_goods.models import *
from df_order.models import *
from django.core.paginator import Paginator,Page

def register(request):
    context={'title':'用户注册'}
    return render(request,'df_user/register.html',context)

def register_handle(request):
    #接收用户输入
    post=request.POST
    uname=post.get('user_name')
    upwd=post.get('pwd')
    upwd2=post.get('cpwd')
    uemail=post.get('email')
    #判断两次密码
    if upwd!=upwd2:
        return redirect('/user/register/')
    #密码加密
    s1=sha1()
    s1.update(upwd)
    upwd3=s1.hexdigest()
    #创建对象
    user=UserInfo()
    user.uname=uname
    user.upwd=upwd3
    user.uemail=uemail
    user.save()
    #注册成功，转到登录页面
    return redirect('/user/login/')

def register_exist(request):
    print 'sdafa'
    uname=request.GET.get('uname')
    count=UserInfo.objects.filter(uname=uname).count()
    return JsonResponse({'count':count})

def login(request):
    uname=request.COOKIES.get('uname','')
    context={'title':'用户登录','error_name': 0,'error_pwd': 0,'uname':uname}
    return render(request,'df_user/login.html',context)

def login_handle(request):
    #接收请求信息
    post=request.POST
    uname=post.get('username')
    upwd=post.get('pwd')
    jizhu=post.get('jizhu',0)
    #根据用户名查询对象
    users=UserInfo.objects.filter(uname=uname)#[]
    print uname
    #判断：如果未查到则用户名错，如果查到则判断密码是否正确，正确则转到用户中心
    if len(users)==1:
        s1=sha1()
        s1.update(upwd)
        if s1.hexdigest()==users[0].upwd:
            url=request.COOKIES.get('url','/')
            red = HttpResponseRedirect(url)
            #成功后删除转向地址，防止以后直接登录造成的转向
            red.set_cookie('url','',max_age=-1)
            #记住用户名
            if jizhu!=0:
                red.set_cookie('uname',uname)
            else:
                red.set_cookie('uname','',max_age=-1)
            request.session['user_id']=users[0].id
            request.session['user_name']=uname
            return red
        else:
            context = {'title': '用户登录','error_name': 0,'error_pwd': 1,'uname':uname,'upwd':upwd}
            return render(request,'df_user/login.html',context)
    else:
        context = {'title': '用户登录','error_name':1,'error_pwd': 0,'uname':uname,'upwd':upwd}
        return render(request,'df_user/login.html',context)

def logout(request):
    request.session.flush()
    return redirect('/')

@user_decorator.login
def info(request):
    user_email=UserInfo.objects.get(id=request.session['user_id']).uemail
    #最近浏览
    goods_list=[]
    goods_ids=request.COOKIES.get('goods_ids','')
    if goods_ids!='':
        goods_ids1=goods_ids.split(',')#['']
        #GoodsInfo.objects.filter(id__in=goods_ids1)
        for goods_id in goods_ids1:
            goods_list.append(GoodsInfo.objects.get(id=int(goods_id)))

    context={'title':'用户中心',
             'user_email':user_email,
             'user_name':request.session['user_name'],
             'page_name':1,
             'goods_list':goods_list}
    return render(request,'df_user/user_center_info.html',context)

@user_decorator.login
def order(request,pindex):
    order_list=OrderInfo.objects.filter(user_id=request.session['user_id']).order_by('-oid')
    paginator=Paginator(order_list,2)
    if pindex=='':
        pindex='1'
    page=paginator.page(int(pindex))

    context={'title':'用户中心',
             'page_name':1,
             'paginator':paginator,
             'page':page,}
    return render(request,'df_user/user_center_order.html',context)

@user_decorator.login
def site(request):
    user = UserInfo.objects.get(id=request.session['user_id'])
    if request.method=='POST':
        post=request.POST
        user.ushou=post.get('ushou')
        user.uaddress=post.get('uaddress')
        user.uyoubian=post.get('uyoubian')
        user.uphone=post.get('uphone')
        user.save()
    context={'title':'用户中心','user':user,
             'page_name':1}
    return render(request,'df_user/user_center_site.html',context)

dailyfresh/templates/df_user/login.html
{%extends 'base_foot.html'%}
{%block head%}
<script>
	$(function(){
	    name_error = false;
	    pwd_error = false;

	    if({{error_name}}==1){
	        $('.user_error').html('用户名错误').show();
		}
		if({{error_pwd}}==1){
	        $('.pwd_error').html('密码错误').show();
		}

		$('.name_input').blur(function(){
		    if($('.name_input').val().length==0){
		        $('.user_error').html('请填写用户名').show();
		        name_error = false;
			}else{
		        $('.user_error').hide();
		        name_error = true;
			}
		});

	    $('.pass_input').blur(function () {
			if($(this).val().length==0){
			    $('.pwd_error').html('请输入密码').show();
			    pwd_error = false;
			}else{
			    $('.pwd_error').hide();
			    pwd_error = true;
			}
        });

	    $('form').submit(function(){
	        $('.name_input').blur();
	        $('.pass_input').blur();
	        return name_error && pwd_error;
		});
	});
</script>
{%endblock head%}

{%block body%}
	<div class="login_top clearfix">
		<a href="/" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form action="/user/login_handle/" method="post">
						{%csrf_token%}
						<input type="text" name="username" class="name_input" value="{{uname}}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" value="{{upwd}}" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="jizhu" value="1" checked="checked">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

{%endblock body%}

dailyfresh/templates/df_user/register.html
{%extends 'base_foot.html'%}

{%block head%}
	<script type="text/javascript" src="/static/js/register.js"></script>
{%endblock head%}

{%block body%}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/user/login/">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="/user/register_handle/" method="post" id="reg_form">
					{%csrf_token%}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册">
					</li>
				</ul>
				</form>
			</div>

		</div>

	</div>
{%endblock body%}

dailyfresh/templates/df_user/user_center_info.html
{%extends 'base.html'%}
{%block content%}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/" class="active">· 个人信息</a></li>
				<li><a href="/user/order/">· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{user_name}}</li>
							<li><span>联系邮箱：</span>{{user_email}}</li>
						</ul>
				</div>

				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
{%for goods in goods_list%}
				<li>
					<a href="/{{goods.id}}/"><img src="/static/{{goods.gpic}}"></a>
					<h4><a href="/{{goods.id}}/">{{goods.gtitle}}</a></h4>
					<div class="operate">
						<span class="prize">￥{{goods.gprice}}</span>
						<span class="unit">{{goods.gprice}}/{{goods.gunit}}</span>
						<a href="/cart/add{{goods.id}}_1/" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
{%endfor%}

			</ul>
		</div>
		</div>
	</div>
{%endblock content%}

dailyfresh/templates/df_user/user_center_order.html
{%extends 'base.html'%}
{%block head%}
<script>
	$(function () {
		$('.col04').each(function () {
			num=parseFloat($(this).prev().text())
			price=parseFloat($(this).prev().prev().find('span').text())
			$(this).text(num*price+'元')
        });
    });
</script>
{%endblock head%}

{%block content%}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/order/" class="active">· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
			<h3 class="common_title2">全部订单</h3>

			{%if paginator.count > 0%}
			{%for order in page%}
			<ul class="order_list_th w978 clearfix">
				<li class="col01">{{order.odate}}</li>
				<li class="col02">订单号：{{order.oid}}</li>
				<li class="col02 stress">{%if order.oIsPay%}已支付{%else%}未支付{%endif%}</li>
			</ul>

			<table class="order_list_table w980">
				<tbody>
					<tr>
						<td width="55%">
							{%for detail in order.orderdetailinfo_set.all%}
							<ul class="order_goods_list clearfix">
								<li class="col01"><img src="/static/{{detail.goods.gpic}}"></li>
								<li class="col02">{{detail.goods.gtitle|slice:'10'}}<em><span>{{detail.price}}</span>元/{{detail.goods.gunit}}</em></li>
								<li class="col03">{{detail.count}}</li>
								<li class="col04">0元</li>
							</ul>
							{%endfor%}
						</td>
						<td width="15%">{{order.ototal}}元</td>
						{%if order.oIsPay%}
						<td width="15%">已付款</td>
						<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
						{%else%}
						<td width="15%">待付款</td>
						<td width="15%"><a href="/order/pay{{order.oid}}/" class="oper_btn">去付款</a></td>
						{%endif%}
					</tr>
				</tbody>
			</table>
			{%endfor%}

			<div class="pagenation">
				{%if page.has_previous%}
				<a href="/user/order{{page.previous_page_number}}/"><上一页</a>
				{%endif%}

				{%for pindex in paginator.page_range%}
				{%if pindex == page.number%}
				<a href="#" class="active">{{pindex}}</a>
				{%else%}
				<a href="/user/order{{pindex}}/">{{pindex}}</a>
				{%endif%}
				{%endfor%}

				{%if page.has_next%}
				<a href="/user/order{{page.next_page_number}}/">下一页></a>
				{%endif%}
				</div>
			{%else%}
			暂无订单信息
			{%endif%}
		</div>
	</div>

{%endblock content%}

dailyfresh/templates/df_user/user_center_site.html
{%extends 'base.html'%}
{%block content%}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/order/">· 全部订单</a></li>
				<li><a href="/user/site/" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{user.uaddress}} （{{user.ushou}} 收） {{user.uphone}}</dd>
					</dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="/user/site/" method="post">
						{%csrf_token%}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="ushou" value="{{user.ushou}}">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="uaddress">{{user.uaddress}}</textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="uyoubian" value="{{user.uyoubian}}">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="uphone" value="{{user.uphone}}">
						</div>

						<input type="submit" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>

{%endblock content%}